### ISSUE TITLE
Please reenable logging to stdout

### ISSUE THREAD

**Issue by baszoetekouw** [IdentityPython/pyFF#124] opened 2018-01-17 16:24 UTC
In https://github.com/leifj/pyFF/commit/c92284aca4839e3a605cbad9143b5f1478ee3254 logging to stdout was disabled entirely (specifically here: https://github.com/leifj/pyFF/blame/master/src/pyff/mdx.py#L818), even when Pyff is not forking and daemonizing.

This is rather inconvenient, for two reasons:
 - it makes development a bit more annoying; I used to be just able to read debugging output on the console, and now I need to redirect to a log file and tail it from there.
 - it makes running pyff in systemd quite messy.  In the old situation, `ExecStart=pyff -f` would Just Work: all logging that was sent to stdout and stderr would end up in the journal, which is easy to manage, to redirect to syslog, etc.

Please either revert to the previous behaviour (`pyff -f` writes logging to stdout) or add a possibility to specify stdout and/or stderr as targets for `--log=` and `--error-log=`.

**Comment by leifj** [comment] 2021-03-30 22:18
I'm going to close this issue since it is referring to code that is about to be deprecated and removed from pyFF, specifically cherrypy. My advise is to make sure logging works as intended in the flask/pygments version and open a new issue if not.

**Closed by leifj** 2021-03-30 22:18 UTC
