### ISSUE TITLE
Problem checking metadata signature with XRD method

### ISSUE THREAD

**Issue by alanbuxey** [IdentityPython/pyFF#194] opened 2020-03-04 13:45 UTC
## Code Version

1.1.2

## Expected Behavior
using the XRD format for load, the metadata URL specified is checked against the embedded certificate.

## Current Behavior
$ pyff test.rd 
ERROR:pyff.samlmd:Error parsing https://www.rediris.es/sir/shib1metadata.xml: Unable to find cert matching fingerprint: 11:43:fd:d6:78:91:37:25:f3:19:95:46:f2:65:f7:6f:96:54:e0:76
---
total size:     0
selected:       0
          idps: 0
           sps: 0
---

## Steps to Reproduce

for bare minimum use the following files

test.rd
```
- load:
   - test.xrd
- select:
- stats:
```

test.xrd
```
<?xml version="1.0"?>
<XRDS xmlns="http://docs.oasis-open.org/ns/xri/xrd-1.0">
    <XRD>
        <Subject>https://www.rediris.es/sir/shib1metadata.xml</Subject>
        <Link rel="urn:oasis:names:tc:SAML:2.0:metadata" href="https://www.rediris.es/sir/shib1metadata.xml">
	<Title>RedIRIS</Title>
            <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
                <ds:X509Data>
                    <ds:X509Certificate>
MIIEKzCCAxOgAwIBAgIEV2ZwSjANBgkqhkiG9w0BAQsFADCBpjEdMBsGCSqGSIb3
DQEJARYOc2lyQHJlZGlyaXMuZXMxCzAJBgNVBAYTAkVTMQ8wDQYDVQQIDAZNYWRy
aWQxDzANBgNVBAcMBk1hZHJpZDEQMA4GA1UECgwHUmVkSVJJUzErMCkGA1UECwwi
U2VydmljaW8gZGUgSWRlbnRpZGFkZXMgZGUgUmVkSVJJUzEXMBUGA1UEAwwOc2ly
LnJlZGlyaXMuZXMwHhcNMTYwNjE5MTAxNzA0WhcNMzEwNjE5MTAxNzA0WjCBrzEd
MBsGCSqGSIb3DQEJARYOc2lyQHJlZGlyaXMuZXMxCzAJBgNVBAYTAkVTMQ8wDQYD
VQQIDAZNYWRyaWQxDzANBgNVBAcMBk1hZHJpZDEQMA4GA1UECgwHUmVkSVJJUzEr
MCkGA1UECwwiU2VydmljaW8gZGUgSWRlbnRpZGFkZXMgZGUgUmVkSVJJUzEgMB4G
A1UEAwwXbWV0YWRhdGEuc2lyLnJlZGlyaXMuZXMwggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQCuHEJzEADRIKz350gJ+Oial4MHXkLrUxlBJcEXgz6TbsLp
mkEJTVMHsC0cwRVQxl6fZ+OF91vTMyNeXujxdlEQakFgjlDxcvWrouIJ6Ewa137z
pQYyyQ8NqDp2cDBMgl1QK21F/AipV7FwX5+6AxWbgxQnJ5op7cVhch/30WQSF6NC
PXoC7xWtS8AguTN0/XKC46GuBBeJLpIbyuyaVqVXc/6xVD99WOAIxPVzK1dRSSCY
9P/y9RXFqjpSeLdSZh1+ClJ/CtRyDbJY13hSWmEqXInMJdkCqeNQDwWXbwMHcMa4
r/UV8HlCul3mQAC8SiBtxtF4WBGHtp3MhjhG3SbRAgMBAAGjVjBUMAwGA1UdEwEB
/wQCMAAwNAYDVR0lAQH/BCowKAYIKwYBBQUHAwEGCCsGAQUFBwMCBggrBgEFBQcD
AwYIKwYBBQUHAwgwDgYDVR0PAQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4IBAQBH
dMNzqm1cJFe5gl2SHxWcJdMY3BKFEUZnox7IWts9N1lQ8y81jgVK0BQopKSgb5oO
TZJc7ZZ/N1AN9OXmQYxVwHVb6uOU3CgavaNcQTfbe+LReoZyLF0octZhRH4scxud
uecyUPsPuCohbos10Hks6QxA7yHuT+eJEWeCto2w5wffm6DB1hz3hr/BokOV77uf
henKbPyRQ50wwFJxzvU/EOiV5IPkYo1cpcnvQF9FygsiwDzQOT2iRzpp5MgPR+Ui
4Bbhnd3fa1BQORXJx3WL+e8wo+rrGkiE5YetjK0JGVCrZq43AuWBIpiI6NUxpicX
bQ2YZvyVwCXApXcr9891
</ds:X509Certificate>
                </ds:X509Data>
            </ds:KeyInfo>
        </Link>
    </XRD>
</XRDS>
```

**Comment by leifj** [comment] 2021-03-30 21:49
the problem is/was that pyXMLSecurity throws a ValueError when it comes up on a cert whose fingerprint isn't among the trusted certs to validate the signature against. This is normally ok but in the case of rediris and uk-fed some EntityDescriptors have their own (invalid) signatures. A fix for this is in IdentityPython/pyXMLSecurity#140808c and will be released

**Closed** 2021-03-30 22:10 UTC
