### ISSUE TITLE
wrong xmlns:mdrpi declaration

### ISSUE THREAD

**Issue by majagw** [IdentityPython/pyFF#101] opened 2017-03-13 13:07 UTC
A wrong xmlns:mdrpi namespace declaration in the RegistrationInfo element causes that the entity with such element is ignored when the selection basing on RegistrationInfo is required, otherwise the entity is passed together with a faulty namespace value.

**Comment by leifj** [comment] 2021-03-30 22:22
Not sure if this is still a concern but since there is nothing I can use to reproduce it I'm closing the issue for now.

**Closed by leifj** 2021-03-30 22:22 UTC
